<a href="https://colab.research.google.com/github/Hamzachaudhary911/Hamzachaudhary911/blob/main/Numpy_Array_Basic_Concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import numpy as np

# **Creating Arrays 1D, 2D, 3D & 4D**

In [66]:
#1 Dimensional Array
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [67]:
# 2 Dimensional Array
arr2=np.array([[1,2,3,4,5],
             [11,12,13,14,15]])
arr2.ndim


2

In [68]:
#3 D Array
arr3=np.array([[[1,2,3,4,5],
             [7,18,19,22,12],
            [898,281,28,0,23]]])
arr3

array([[[  1,   2,   3,   4,   5],
        [  7,  18,  19,  22,  12],
        [898, 281,  28,   0,  23]]])

In [69]:
#Check the Type of an array
type(arr1)

numpy.ndarray

In [70]:
#Check the shape of an array
arr1.shape

(4,)

In [71]:
#Check the size of an array
arr1.size

4

# **Indexing and Slicing**

In [72]:
arr2

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [92]:
#Accessing 3,4,5
arr2[0,2:]

array([3, 4, 5])

In [91]:
arr1[2]=109
arr1[1]

2

In [73]:
# Want to access 14, 15
arr2[1,3:]

array([14, 15])

In [74]:
# Want to access (1,2) and (13,14)
print(arr2[0,0:2])
print(arr2[1,2:4])

[1 2]
[13 14]


In [77]:
arr3

array([[[  1,   2,   3,   4,   5],
        [  7,  18,  19,  22,  12],
        [898, 281,  28,   0,  23]]])

In [118]:
# Want to get 18,19 and 281,28
arr3[0,1:,1:3]

array([[ 18,  19],
       [281,  28]])

**Indexing on 3D Array**

In [96]:
array3=np.array([[['Hamza','Haroon','Asad','Zain'],
                ['Haji','Lahore','Juniad','Saad']],
                [['Kamran','Bilal','Noman','Ali'],
                ['Waqas','Usman','Masood','Aslam']],
                [['Zakrya','Beenish','Omar','Ameer'],
                ['Kubra','Faryal','Tahir','Rizwan']]])
array3


array([[['Hamza', 'Haroon', 'Asad', 'Zain'],
        ['Haji', 'Lahore', 'Juniad', 'Saad']],

       [['Kamran', 'Bilal', 'Noman', 'Ali'],
        ['Waqas', 'Usman', 'Masood', 'Aslam']],

       [['Zakrya', 'Beenish', 'Omar', 'Ameer'],
        ['Kubra', 'Faryal', 'Tahir', 'Rizwan']]], dtype='<U7')

In [101]:
array3[0, 1, 1:3]

array(['Lahore', 'Juniad'], dtype='<U7')

In [104]:
d3=np.array([[[1,2,3,4],
              [5,6,7,8]],
             [[11,44,33,8],
             [7,46,101,77]]])
d3

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8]],

       [[ 11,  44,  33,   8],
        [  7,  46, 101,  77]]])

In [107]:
d3[0:2,1,1:4:2]

array([[ 6,  8],
       [46, 77]])

In [106]:
d3[0:2,0:,2:]

array([[[  3,   4],
        [  7,   8]],

       [[ 33,   8],
        [101,  77]]])

In [110]:
arr4=([[[[1,2,3,4],
         [5,6,7,8],
        [11,299,98,67],
         [99,17,90,11]],

        [[11,22,33,44],
         [45,67,89,43],
         [98,76,55,34],
         [99,108,565,555]],

         [[111,222,333,444],
        [999,888,777,666],
          [234,56666,1801,7161],
          [1,9,87,12]]],

      [[[1,23,31,4],
         [5,609,7,8],
        [101,219,98,67],
         [919,1767,90,11]],

        [[11,22,33,424],
         [4915,67,819,43],
         [9828,76,535,34],
         [99,108,265,555]],

         [[191,292,333,444],
        [909,808,747,626],
          [3434,566,10,761],
            [1,9,87,12]]]])
arr4

[[[[1, 2, 3, 4], [5, 6, 7, 8], [11, 299, 98, 67], [99, 17, 90, 11]],
  [[11, 22, 33, 44], [45, 67, 89, 43], [98, 76, 55, 34], [99, 108, 565, 555]],
  [[111, 222, 333, 444],
   [999, 888, 777, 666],
   [234, 56666, 1801, 7161],
   [1, 9, 87, 12]]],
 [[[1, 23, 31, 4], [5, 609, 7, 8], [101, 219, 98, 67], [919, 1767, 90, 11]],
  [[11, 22, 33, 424],
   [4915, 67, 819, 43],
   [9828, 76, 535, 34],
   [99, 108, 265, 555]],
  [[191, 292, 333, 444],
   [909, 808, 747, 626],
   [3434, 566, 10, 761],
   [1, 9, 87, 12]]]]

In [116]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [117]:
arr[1,-1]

10

# **DataTypes**

In [123]:
array=np.array([1.2,2.5,6.7])
array.dtype


dtype('float64')

In [128]:
array=np.array(['AJK','LAHORE','LONDON'])
array.dtype


dtype('<U6')

In [130]:
arr = np.array([1, 0, 3])
arr.astype(bool)

array([ True, False,  True])

In [131]:
arr1=np.arange(1,10)
arr1.astype(float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

# **Copy vs View**

In [136]:
#Copy of an array
a=np.array([1,2,3,4,5])
b= a.copy()
a[1]=10
print(a)
print(b)

[ 1 10  3  4  5]
[1 2 3 4 5]


In [141]:
#View of an array
array=np.arange(1,11)
arr1=array.view()
array[4:7]=190
print(array)
print(arr1)

[  1   2   3   4 190 190 190   8   9  10]
[  1   2   3   4 190 190 190   8   9  10]


# **Joining Array**

In [146]:
array1=np.array([[1,2,],[4,6]])
array2=np.array([[90,18],[11,23]])
array=np.concatenate((array1,array2),axis=0)
array

array([[ 1,  2],
       [ 4,  6],
       [90, 18],
       [11, 23]])

In [147]:
array1=np.array([[1,2,],[4,6]])
array2=np.array([[90,18],[11,23]])
array=np.concatenate((array1,array2),axis=1)
array

array([[ 1,  2, 90, 18],
       [ 4,  6, 11, 23]])

In [153]:
#Using Stack Function
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2),axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [162]:
a=np.array([[1,2],[44,55]])
b=np.array([[11,22],[99,33]])
a1=np.concatenate((a,b),axis=1)
a1

array([[ 1,  2, 11, 22],
       [44, 55, 99, 33]])

# **Splitting Array**

In [166]:
a=np.array([[1,2,3],[78,99,11],[76,909,44],[1100,8,43],[111,222,3333]])
c=np.array_split(a,4)
c

[array([[ 1,  2,  3],
        [78, 99, 11]]),
 array([[ 76, 909,  44]]),
 array([[1100,    8,   43]]),
 array([[ 111,  222, 3333]])]

# **Searching Numpy Arrays**

In [169]:
#Find Even Numbers
a1=np.arange(1,41)
b1=np.where(a1%2==0)
print(b1)
a2=np.array([1,2,3,4,5,6,7,8,9,10])
b2=np.where(a2%2==0)
b2

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39]),)


(array([1, 3, 5, 7, 9]),)